### ISSUE TITLE
请问预训练模型可以提供一下吗

### ISSUE THREAD

**Issue by daixiaolei623** [TotalVariation/Flattenet#1]
您好，谢谢你的分享，
请问可以提供一下预训练模型../pretrained_models/imagenet/resnetv1s_101.pth吗
谢谢。

**Comment by TotalVariation** [comment]
感谢对我们工作的兴趣。请使用以下链接获取pre-trained model (restnetv1s_101.pth) weights (tarball):
https://drive.google.com/file/d/1AvNsNdJtjIq6PqSISvIgBmq-FYSAdbZ0/view?usp=sharing
(请尽快下载以免链接失效)

**Comment by daixiaolei623** [comment]
您好，请问可以分享一下那个在pascal-voc2012 上mIoU达到85.69的模型吗，我是一名计科的大学生，想学习一下这个模型。
谢谢













在 2021-04-12 16:22:33，"TotalVariation" ***@***.***> 写道：

感谢对我们工作的兴趣。请使用以下链接获取pre-trained model (restnetv1s_101.pth) weights (tarball):
https://drive.google.com/file/d/1AvNsNdJtjIq6PqSISvIgBmq-FYSAdbZ0/view?usp=sharing
(请尽快下载以免链接失效)
